// skinsData.js - CS2 items data definitions: Knives, Skins, Gloves, Weapons, Wears

(function (root) {
  const CS2_DATA = {
    KNIFE_MODELS: [
      { regex: /\bm9\s*(?:bayonet(?:\s+knife)?)?\b/i, name: "M9 Bayonet Knife", generic: false },
      { regex: /\bshadow\s+daggers?(?:\s+knife)?\b/i, name: "Shadow Daggers Knife", generic: false },
      { regex: /\bbowie(?:\s+knife)?\b/i, name: "Bowie Knife", generic: false },
      { regex: /\b(?:butterfly(?:\s+knife)?|bfk)\b/i, name: "Butterfly Knife", generic: false },
      { regex: /\bfalchion(?:\s+knife)?\b/i, name: "Falchion Knife", generic: false },
      { regex: /\bhuntsman(?:\s+knife)?\b/i, name: "Huntsman Knife", generic: false },
      { regex: /\b(?:karambit(?:\s+knife)?|kara)\b/i, name: "Karambit Knife", generic: false },
      { regex: /\bkukri(?:\s+knife)?\b/i, name: "Kukri Knife", generic: false },
      { regex: /\bbayonet(?:\s+knife)?\b/i, name: "Bayonet Knife", generic: false },
      { regex: /\bnavaja(?:\s+knife)?\b/i, name: "Navaja Knife", generic: false },
      { regex: /\bparacord(?:\s+knife)?\b/i, name: "Paracord Knife", generic: false },
      { regex: /\bstiletto(?:\s+knife)?\b/i, name: "Stiletto Knife", generic: false },
      { regex: /\btalon(?:\s+knife)?\b/i, name: "Talon Knife", generic: false },
      { regex: /\bursus(?:\s+knife)?\b/i, name: "Ursus Knife", generic: false },
      // Generic English words used as knife names
      { regex: /\bclassic(?:\s+knife)?\b/i, explicitRegex: /\bclassic\s+knife\b/i, name: "Classic Knife", generic: true },
      { regex: /\bflip(?:\s+knife)?\b/i, explicitRegex: /\bflip\s+knife\b/i, name: "Flip Knife", generic: true },
      { regex: /\bgut(?:\s+knife)?\b/i, explicitRegex: /\bgut\s+knife\b/i, name: "Gut Knife", generic: true },
      { regex: /\bnomad(?:\s+knife)?\b/i, explicitRegex: /\bnomad\s+knife\b/i, name: "Nomad Knife", generic: true },
      { regex: /\bskeleton(?:\s+knife)?\b/i, explicitRegex: /\bskeleton\s+knife\b/i, name: "Skeleton Knife", generic: true },
      { regex: /\bsurvival(?:\s+knife)?\b/i, explicitRegex: /\bsurvival\s+knife\b/i, name: "Survival Knife", generic: true },
    ],

    KNIFE_SKINS: [
      // Multi-word skins first
      { regex: /\bgamma\s+doppler\b/i, name: "Gamma Doppler" },
      { regex: /\bmarble\s+fade\b/i, name: "Marble Fade" },
      { regex: /\bblack\s+laminate\b/i, name: "Black Laminate" },
      { regex: /\bblue\s+steel\b/i, name: "Blue Steel" },
      { regex: /\bboreal\s+forest\b/i, name: "Boreal Forest" },
      { regex: /\bbright\s+water\b/i, name: "Bright Water" },
      { regex: /\bcase\s+hardened\b/i, name: "Case Hardened" },
      { regex: /\bcrimson\s+web\b/i, name: "Crimson Web" },
      { regex: /\bdamascus\s+steel\b/i, name: "Damascus Steel" },
      { regex: /\bforest\s+ddpat\b/i, name: "Forest DDPAT" },
      { regex: /\bnight\s+stripe\b/i, name: "Night Stripe" },
      { regex: /\brust\s+coat\b/i, name: "Rust Coat" },
      { regex: /\bsafari\s+mesh\b/i, name: "Safari Mesh" },
      { regex: /\btiger\s+tooth\b/i, name: "Tiger Tooth" },
      { regex: /\burban\s+masked\b/i, name: "Urban Masked" },
      // Single-word skins
      { regex: /\bautotronic\b/i, name: "Autotronic" },
      { regex: /\bdoppler\b/i, name: "Doppler" },
      { regex: /\bfade\b/i, name: "Fade" },
      { regex: /\bfreehand\b/i, name: "Freehand" },
      { regex: /\blore\b/i, name: "Lore" },
      { regex: /\bnight\b/i, name: "Night" },
      { regex: /\bscorched\b/i, name: "Scorched" },
      { regex: /\bslaughter\b/i, name: "Slaughter" },
      { regex: /\bstained\b/i, name: "Stained" },
      { regex: /\bultraviolet\b/i, name: "Ultraviolet" },
      { regex: /\bvanilla\b/i, name: "Vanilla" },
    ],

    GLOVE_MODELS: [
      { regex: /\bbloodhound(?:(?:\s+leather)?\s+gloves?)?\b/i, name: "Bloodhound Gloves", generic: false },
      { regex: /\bbroken\s+fang(?:\s+gloves?)?\b/i, name: "Broken Fang Gloves", generic: false },
      { regex: /\bhand\s*wraps?(?:\s+gloves?)?\b/i, name: "Hand Wraps", generic: false },
      { regex: /\bhydra(?:\s+gloves?)?\b/i, explicitRegex: /\bhydra\s+gloves?\b/i, name: "Hydra Gloves", generic: true },
      { regex: /\bmoto(?:\s+gloves?)?\b/i, name: "Moto Gloves", generic: false },
      // Generic English words used as glove names
      { regex: /\bdriver(?:\s+gloves?)?\b/i, explicitRegex: /\bdriver\s+gloves?\b/i, name: "Driver Gloves", generic: true },
      { regex: /\bspecialist(?:\s+gloves?)?\b/i, explicitRegex: /\bspecialist\s+gloves?\b/i, name: "Specialist Gloves", generic: true },
      { regex: /\bsport(?:s)?(?:\s+gloves?)?\b/i, explicitRegex: /\bsport(?:s)?\s+gloves?\b/i, name: "Sport Gloves", generic: true },
    ],

    GLOVE_SKINS: [
      // Multi-word skins first
      { regex: /\bchocolate\s+chesterfield\b/i, name: "Chocolate Chesterfield" },
      { regex: /\b3rd\s+commando\s+company\b/i, name: "3rd Commando Company" },
      { regex: /\bbrocade\s+flowers\b/i, name: "Brocade Flowers" },
      { regex: /\bpillow\s+punchers\b/i, name: "Pillow Punchers" },
      { regex: /\bcreme\s+pinstripe\b/i, name: "Creme Pinstripe" },
      { regex: /\bscarlet\s+shamagh\b/i, name: "Scarlet Shamagh" },
      { regex: /\bviolet\s+beadwork\b/i, name: "Violet Beadwork" },
      { regex: /\bimperial\s+plaid\b/i, name: "Imperial Plaid" },
      { regex: /\bdesert\s+shamagh\b/i, name: "Desert Shamagh" },
      { regex: /\bblood\s+pressure\b/i, name: "Blood Pressure" },
      { regex: /\bcrimson\s+kimono\b/i, name: "Crimson Kimono" },
      { regex: /\byellow[- ]banded\b/i, name: "Yellow-banded" },
      { regex: /\bbrocade\s+crane\b/i, name: "Brocade Crane" },
      { regex: /\bcrimson\s+weave\b/i, name: "Crimson Weave" },
      { regex: /\bhand\s+sweaters\b/i, name: "Hand Sweaters" },
      { regex: /\brezan\s+the\s+red\b/i, name: "Rezan the Red" },
      { regex: /\bcobalt\s+skulls\b/i, name: "Cobalt Skulls" },
      { regex: /\bcase\s+hardened\b/i, name: "Case Hardened" },
      { regex: /\blt\.?\s*commander\b/i, name: "Lt. Commander" },
      { regex: /\bpandora(?:'s)?\s+box\b/i, name: "Pandora's Box" },
      { regex: /\bultra[\s-]?violent\b/i, name: "Ultra Violent" },
      { regex: /\bneedle\s+point\b/i, name: "Needle Point" },
      { regex: /\bdragon\s+fists\b/i, name: "Dragon Fists" },
      { regex: /\bqueen\s+jaguar\b/i, name: "Queen Jaguar" },
      { regex: /\bracing\s+green\b/i, name: "Racing Green" },
      { regex: /\bsnow\s+leopard\b/i, name: "Snow Leopard" },
      { regex: /\bspruce\s+ddpat\b/i, name: "Spruce DDPAT" },
      { regex: /\bcloud\s+chaser\b/i, name: "Cloud Chaser" },
      { regex: /\bforest\s+ddpat\b/i, name: "Forest DDPAT" },
      { regex: /\blime\s+polycam\b/i, name: "Lime Polycam" },
      { regex: /\btiger\s+strike\b/i, name: "Tiger Strike" },
      { regex: /\bbronze\s+morph\b/i, name: "Bronze Morph" },
      { regex: /\blunar\s+weave\b/i, name: "Lunar Weave" },
      { regex: /\bwave\s+chaser\b/i, name: "Wave Chaser" },
      { regex: /\bfinish\s+line\b/i, name: "Finish Line" },
      { regex: /\bcrimson\s+web\b/i, name: "Crimson Web" },
      { regex: /\bemerald\s+web\b/i, name: "Emerald Web" },
      { regex: /\bfield\s+agent\b/i, name: "Field Agent" },
      { regex: /\bmarble\s+fade\b/i, name: "Marble Fade" },
      { regex: /\bking\s+snake\b/i, name: "King Snake" },
      { regex: /\bplum\s+quill\b/i, name: "Plum Quill" },
      { regex: /\bhedge\s+maze\b/i, name: "Hedge Maze" },
      { regex: /\bblack\s+tie\b/i, name: "Black Tie" },
      { regex: /\bduct\s+tape\b/i, name: "Duct Tape" },
      { regex: /\bcool\s+mint\b/i, name: "Cool Mint" },
      { regex: /\bsmoke\s+out\b/i, name: "Smoke Out" },
      { regex: /\bbig\s+swell\b/i, name: "Big Swell" },
      { regex: /\bred\s+racer\b/i, name: "Red Racer" },
      { regex: /\bcaution!?\b/i, name: "CAUTION!" },
      { regex: /\bbig\s+game\b/i, name: "Big Game" },
      { regex: /\bboom!?\b/i, name: "Boom!" },
      { regex: /\bpow!?\b/i, name: "POW!" },
      // Single-word skins
      { regex: /\bamphibious\b/i, name: "Amphibious" },
      { regex: /\barboreal\b/i, name: "Arboreal" },
      { regex: /\barid\b/i, name: "Arid" },
      { regex: /\bbadlands\b/i, name: "Badlands" },
      { regex: /\bblackbook\b/i, name: "Blackbook" },
      { regex: /\bblaze\b/i, name: "Blaze" },
      { regex: /\bbronzed\b/i, name: "Bronzed" },
      { regex: /\bbuckshot\b/i, name: "Buckshot" },
      { regex: /\bcharred\b/i, name: "Charred" },
      { regex: /\bconstrictor\b/i, name: "Constrictor" },
      { regex: /\bconvoy\b/i, name: "Convoy" },
      { regex: /\bdiamondback\b/i, name: "Diamondback" },
      { regex: /\beclipse\b/i, name: "Eclipse" },
      { regex: /\bemerald\b/i, name: "Emerald" },
      { regex: /\bfade\b/i, name: "Fade" },
      { regex: /\bfoundation\b/i, name: "Foundation" },
      { regex: /\bfrosty\b/i, name: "Frosty" },
      { regex: /\bgarden\b/i, name: "Garden" },
      { regex: /\bgiraffe\b/i, name: "Giraffe" },
      { regex: /\bguerrilla\b/i, name: "Guerrilla" },
      { regex: /\bjade\b/i, name: "Jade" },
      { regex: /\bleather\b/i, name: "Leather" },
      { regex: /\bmangrove\b/i, name: "Mangrove" },
      { regex: /\bmogul\b/i, name: "Mogul" },
      { regex: /\bnocts\b/i, name: "Nocts" },
      { regex: /\boccult\b/i, name: "Occult" },
      { regex: /\bomega\b/i, name: "Omega" },
      { regex: /\boverprint\b/i, name: "Overprint" },
      { regex: /\bovertake\b/i, name: "Overtake" },
      { regex: /\bpolygon\b/i, name: "Polygon" },
      { regex: /\brattler\b/i, name: "Rattler" },
      { regex: /\bseigaiha\b/i, name: "Seigaiha" },
      { regex: /\bslaughter\b/i, name: "Slaughter" },
      { regex: /\bslingshot\b/i, name: "Slingshot" },
      { regex: /\bsnakebite\b/i, name: "Snakebite" },
      { regex: /\bspearmint\b/i, name: "Spearmint" },
      { regex: /\bsunburst\b/i, name: "Sunburst" },
      { regex: /\bsuperconductor\b/i, name: "Superconductor" },
      { regex: /\btransport\b/i, name: "Transport" },
      { regex: /\bturtle\b/i, name: "Turtle" },
      { regex: /\bunhinged\b/i, name: "Unhinged" },
      { regex: /\bvice\b/i, name: "Vice" },
    ],

    GLOVES: [
      { regex: /\bbloodhound(?:(?:\s+leather)?\s+gloves?)?\b/i, name: "Bloodhound Gloves" },
      { regex: /\bbroken\s+fang(?:\s+gloves?)?\b/i, name: "Broken Fang Gloves" },
      { regex: /\bdriver(?:\s+gloves?)?\b/i, name: "Driver Gloves" },
      { regex: /\bhand\s*wraps?(?:\s+gloves?)?\b/i, name: "Hand Wraps" },
      { regex: /\bhydra(?:\s+gloves?)?\b/i, name: "Hydra Gloves" },
      { regex: /\bmoto(?:\s+gloves?)?\b/i, name: "Moto Gloves" },
      { regex: /\bspecialist(?:\s+gloves?)?\b/i, name: "Specialist Gloves" },
      { regex: /\bsport(?:s)?(?:\s+gloves?)?\b/i, name: "Sport Gloves" },
    ],

    WEAPONS: [
      { regex: /\bak[- ]?47\b/i, name: "AK-47" },
      { regex: /\bm4a1[- ]?s\b/i, name: "M4A1-S" },
      { regex: /\bm4a4\b/i, name: "M4A4" },
      { regex: /\bm4a1\b/i, name: "M4A1" },
      { regex: /\bawp\b/i, name: "AWP" },
      { regex: /\bdesert\s+eagle\b/i, name: "Desert Eagle" },
      { regex: /\bdeagle\b/i, name: "Deagle" },
      { regex: /\busp[- ]?s\b/i, name: "USP-S" },
      { regex: /\busp\b/i, name: "USP" },
      { regex: /\bglock(?:[- ]?18)?\b/i, name: "Glock" },
      { regex: /\bgalil(?:[- ]?ar)?\b/i, name: "Galil" },
      { regex: /\bfamas\b/i, name: "FAMAS" },
      { regex: /\bmp9\b/i, name: "MP9" },
      { regex: /\bmac[- ]?10\b/i, name: "MAC-10" },
      { regex: /\bp250\b/i, name: "P250" },
      { regex: /\bfive[- ]?seven\b/i, name: "Five-SeveN" },
      { regex: /\bcz75(?:[- ]?auto)?\b/i, name: "CZ75-Auto" },
      { regex: /\btec[- ]?9\b/i, name: "Tec-9" },
      { regex: /\bssg(?:[- ]?08)?\b/i, name: "SSG 08" },
      { regex: /\bscout\b/i, name: "Scout" },
      { regex: /\bsg[- ]?553\b/i, name: "SG 553" },
      { regex: /\baug\b/i, name: "AUG" },
      { regex: /\bmp7\b/i, name: "MP7" },
      { regex: /\bp90\b/i, name: "P90" },
      { regex: /\bump(?:[- ]?45)?\b/i, name: "UMP-45" },
      { regex: /\b(?:pp[- ]?)?bizon\b/i, name: "PP-Bizon" },
      { regex: /\bnova\b/i, name: "Nova" },
      { regex: /\bxm1014\b/i, name: "XM1014" },
      { regex: /\bmag[- ]?7\b/i, name: "MAG-7" },
      { regex: /\bsawed[- ]?off\b/i, name: "Sawed-Off" },
      { regex: /\bm249\b/i, name: "M249" },
      { regex: /\bnegev\b/i, name: "Negev" },
      { regex: /\bg3sg1\b/i, name: "G3SG1" },
      { regex: /\bscar[- ]?20\b/i, name: "SCAR-20" },
    ],

    WEARS: [
      { regex: /\b(?:factory[\s_-]?new|fn)\b/i, abbr: "FN", fullName: "Factory New" },
      { regex: /\b(?:minimal[\s_-]?wear|mw)\b/i, abbr: "MW", fullName: "Minimal Wear" },
      { regex: /\b(?:field[\s_-]?tested|ft(?!\s*[@.]))\b/i, abbr: "FT", fullName: "Field-Tested" },
      { regex: /\b(?:well[\s_-]?worn|ww)\b/i, abbr: "WW", fullName: "Well-Worn" },
      { regex: /\b(?:battle[\s_-]?scarred|bs)\b/i, abbr: "BS", fullName: "Battle-Scarred" },
    ],

    CS2_HINTS: [
      /\bcs2\b/i,
      /\bcsgo\b/i,
      /\bfactory[\s_-]?new\b/i,
      /\bminimal[\s_-]?wear\b/i,
      /\bfield[\s_-]?tested\b/i,
      /\bwell[\s_-]?worn\b/i,
      /\bbattle[\s_-]?scarred\b/i,
      /\bfn\b/i,
      /\bmw\b/i,
      /\bft(?!\s*[@.])\b/i,
      /\bww\b/i,
      /\bbs\b/i,
    ],

    STEAM_KNIFE_WEAPONS: {
      "Bayonet Knife": "Bayonet",
      "M9 Bayonet Knife": "M9 Bayonet",
      "Karambit Knife": "Karambit",
      "Shadow Daggers Knife": "Shadow Daggers",
      "Bowie Knife": "Bowie Knife",
      "Butterfly Knife": "Butterfly Knife",
      "Classic Knife": "Classic Knife",
      "Falchion Knife": "Falchion Knife",
      "Flip Knife": "Flip Knife",
      "Gut Knife": "Gut Knife",
      "Huntsman Knife": "Huntsman Knife",
      "Kukri Knife": "Kukri Knife",
      "Navaja Knife": "Navaja Knife",
      "Nomad Knife": "Nomad Knife",
      "Paracord Knife": "Paracord Knife",
      "Skeleton Knife": "Skeleton Knife",
      "Stiletto Knife": "Stiletto Knife",
      "Survival Knife": "Survival Knife",
      "Talon Knife": "Talon Knife",
      "Ursus Knife": "Ursus Knife",
    },

    WEAPON_MODELS: [
      { regex: /\bak[- ]?47\b/i, shortRegex: /\bak\b/i, name: "AK-47" },
      { regex: /\bawp\b/i, shortRegex: /\bawp\b/i, name: "AWP" },
      { regex: /\bm4a1[- ]?s\b|\bm4[- ]?a1[- ]?s\b|\bm4a1\b/i, shortRegex: /\bm4\b/i, name: "M4A1-S" },
      { regex: /\bm4a4\b|\bm4[- ]?a4\b/i, shortRegex: /\bm4\b/i, name: "M4A4" },
    ],

    WEAPON_SKINS: {
      "AK-47": [
        { regex: /\bConsequence\s+of\s+the\s+Jinn\b/i, name: "Consequence of the Jinn" },
        { regex: /\bAquamarine\s+Revenge\b/i, name: "Aquamarine Revenge" },
        { regex: /\bEmerald\s+Pinstripe\b/i, name: "Emerald Pinstripe" },
        { regex: /\bMidnight\s+Laminate\b/i, name: "Midnight Laminate" },
        { regex: /\bPhantom\s+Disruptor\b/i, name: "Phantom Disruptor" },
        { regex: /\bLegion\s+of\s+Anubis\b/i, name: "Legion of Anubis" },
        { regex: /\bFrontside\s+Misty\b/i, name: "Frontside Misty" },
        { regex: /\bNeon\s+Revolution\b/i, name: "Neon Revolution" },
        { regex: /\bWasteland\s+Rebel\b/i, name: "Wasteland Rebel" },
        { regex: /\bBaroque\s+Purple\b/i, name: "Baroque Purple" },
        { regex: /\bBlack\s+Laminate\b/i, name: "Black Laminate" },
        { regex: /\bGold\s+Arabesque\b/i, name: "Gold Arabesque" },
        { regex: /\bGreen\s+Laminate\b/i, name: "Green Laminate" },
        { regex: /\bPoint\s+Disarray\b/i, name: "Point Disarray" },
        { regex: /\bBlue\s+Laminate\b/i, name: "Blue Laminate" },
        { regex: /\bB\s+the\s+Monster\b/i, name: "B the Monster" },
        { regex: /\bCase\s+Hardened\b/i, name: "Case Hardened" },
        { regex: /\bFuel\s+Injector\b/i, name: "Fuel Injector" },
        { regex: /\bNouveau\s+Rouge\b/i, name: "Nouveau Rouge" },
        { regex: /\bOlive\s+Polycam\b/i, name: "Olive Polycam" },
        { regex: /\bPanthera\s+onca\b/i, name: "Panthera onca" },
        { regex: /\bThe\s+Outsiders\b/i, name: "The Outsiders" },
        { regex: /\bvaricamo\s+gr[ea]y\b/i, name: "VariCamo Grey" },
        { regex: /\bCrane\s+Flight\b/i, name: "Crane Flight" },
        { regex: /\bFire\s+Serpent\b/i, name: "Fire Serpent" },
        { regex: /\bJungle\s+Spray\b/i, name: "Jungle Spray" },
        { regex: /\bRed\s+Laminate\b/i, name: "Red Laminate" },
        { regex: /\bSearing\s+Rage\b/i, name: "Searing Rage" },
        { regex: /\bThe\s+Oligarch\b/i, name: "The Oligarch" },
        { regex: /\bElite\s+Build\b/i, name: "Elite Build" },
        { regex: /\bFirst\s+Class\b/i, name: "First Class" },
        { regex: /\bSafari\s+Mesh\b/i, name: "Safari Mesh" },
        { regex: /\bSteel\s+Delta\b/i, name: "Steel Delta" },
        { regex: /\bThe\s+Empress\b/i, name: "The Empress" },
        { regex: /\bIce\s+Coaled\b/i, name: "Ice Coaled" },
        { regex: /\bLeet\s+Museo\b/i, name: "Leet Museo" },
        { regex: /\bNeon\s+Rider\b/i, name: "Neon Rider" },
        { regex: /\borbit\s+mk0?1\b/i, name: "Orbit Mk01" },
        { regex: /\bSafety\s+Net\b/i, name: "Safety Net" },
        { regex: /\bWild\s+Lotus\b/i, name: "Wild Lotus" },
        { regex: /\bHead\s+Shot\b/i, name: "Head Shot" },
        { regex: /\bJet\s+Set\b/i, name: "Jet Set" },
        { regex: /\bRat\s+Rod\b/i, name: "Rat Rod" },
        { regex: /\bX[- ]Ray\b/i, name: "X-Ray" },
        { regex: /\bBreakthrough\b/i, name: "Breakthrough" },
        { regex: /\bInheritance\b/i, name: "Inheritance" },
        { regex: /\bWintergreen\b/i, name: "Wintergreen" },
        { regex: /\bBloodsport\b/i, name: "Bloodsport" },
        { regex: /\bHydroponic\b/i, name: "Hydroponic" },
        { regex: /\bAphrodite\b/i, name: "Aphrodite" },
        { regex: /\bCrossfade\b/i, name: "Crossfade" },
        { regex: /\bNightwish\b/i, name: "Nightwish" },
        { regex: /\bUncharted\b/i, name: "Uncharted" },
        { regex: /\bAUTOEXEC\b/i, name: "AUTOEXEC" },
        { regex: /\bPredator\b/i, name: "Predator" },
        { regex: /\bAsiimov\b/i, name: "Asiimov" },
        { regex: /\bRedline\b/i, name: "Redline" },
        { regex: /\bCartel\b/i, name: "Cartel" },
        { regex: /\bJaguar\b/i, name: "Jaguar" },
        { regex: /\bVulcan\b/i, name: "Vulcan" },
        { regex: /\bSlate\b/i, name: "Slate" },
      ],
      "AWP": [
        { regex: /\bChromatic\s+Aberration\b/i, name: "Chromatic Aberration" },
        { regex: /\bContainment\s+Breach\b/i, name: "Containment Breach" },
        { regex: /\bLightning\s+Strike\b/i, name: "Lightning Strike" },
        { regex: /\bSovereign\s+Flame\b/i, name: "Sovereign Flame" },
        { regex: /\bqueen(?:'s|s)?\s+gambit\b/i, name: "Queen's Gambit" },
        { regex: /\bArsenic\s+Spill\b/i, name: "Arsenic Spill" },
        { regex: /\bChrome\s+Cannon\b/i, name: "Chrome Cannon" },
        { regex: /\bElectric\s+Hive\b/i, name: "Electric Hive" },
        { regex: /\bDesert\s+Hydra\b/i, name: "Desert Hydra" },
        { regex: /\bGreen\s+Energy\b/i, name: "Green Energy" },
        { regex: /\bDragon\s+Lore\b/i, name: "Dragon Lore" },
        { regex: /\bElite\s+Build\b/i, name: "Elite Build" },
        { regex: /\bFever\s+Dream\b/i, name: "Fever Dream" },
        { regex: /\bHyper\s+Beast\b/i, name: "Hyper Beast" },
        { regex: /\bSafari\s+Mesh\b/i, name: "Safari Mesh" },
        { regex: /\bBlack\s+Nile\b/i, name: "Black Nile" },
        { regex: /\bIce\s+Coaled\b/i, name: "Ice Coaled" },
        { regex: /\bman[-\s]*o['-\s]+war\b/i, name: "Man-o'-war" },
        { regex: /\bPink\s+DDPAT\b/i, name: "Pink DDPAT" },
        { regex: /\bSilk\s+Tiger\b/i, name: "Silk Tiger" },
        { regex: /\bSnake\s+Camo\b/i, name: "Snake Camo" },
        { regex: /\bSun\s+in\s+Leo\b/i, name: "Sun in Leo" },
        { regex: /\bThe\s+Prince\b/i, name: "The Prince" },
        { regex: /\bBlack\s+Box\b/i, name: "Black Box" },
        { regex: /\bOni\s+Taiji\b/i, name: "Oni Taiji" },
        { regex: /\bPit\s+Viper\b/i, name: "Pit Viper" },
        { regex: /\bNeo[- ]Noir\b/i, name: "Neo-Noir" },
        { regex: /\bWorm\s+God\b/i, name: "Worm God" },
        { regex: /\bPOP\s+AWP\b/i, name: "POP AWP" },
        { regex: /\bThe\s+End\b/i, name: "The End" },
        { regex: /\bExoskeleton\b/i, name: "Exoskeleton" },
        { regex: /\bPrintstream\b/i, name: "Printstream" },
        { regex: /\bExothermic\b/i, name: "Exothermic" },
        { regex: /\bCapillary\b/i, name: "Capillary" },
        { regex: /\bCorticera\b/i, name: "Corticera" },
        { regex: /\bGraphite\b/i, name: "Graphite" },
        { regex: /\bWildfire\b/i, name: "Wildfire" },
        { regex: /\bAcheron\b/i, name: "Acheron" },
        { regex: /\bAsiimov\b/i, name: "Asiimov" },
        { regex: /\bAtheris\b/i, name: "Atheris" },
        { regex: /\bcrakow!?\b/i, name: "Crakow!" },
        { regex: /\bDuality\b/i, name: "Duality" },
        { regex: /\bGungnir\b/i, name: "Gungnir" },
        { regex: /\bLongDog\b/i, name: "LongDog" },
        { regex: /\bRedline\b/i, name: "Redline" },
        { regex: /\bMedusa\b/i, name: "Medusa" },
        { regex: /\bMortis\b/i, name: "Mortis" },
        { regex: /\bPhobos\b/i, name: "Phobos" },
        { regex: /\bboom!?\b/i, name: "BOOM" },
        { regex: /\bCMYK\b/i, name: "CMYK" },
        { regex: /\bFade\b/i, name: "Fade" },
        { regex: /\bPAW\b/i, name: "PAW" },
      ],
      "M4A1-S": [
        { regex: /\bWelcome\s+to\s+the\s+Jungle\b/i, name: "Welcome to the Jungle" },
        { regex: /\bMecha\s+Industries\b/i, name: "Mecha Industries" },
        { regex: /\bchantico(?:'s|s)?\s+fire\b/i, name: "Chantico's Fire" },
        { regex: /\bImminent\s+Danger\b/i, name: "Imminent Danger" },
        { regex: /\bGlitched\s+Paint\b/i, name: "Glitched Paint" },
        { regex: /\bBlue\s+Phosphor\b/i, name: "Blue Phosphor" },
        { regex: /\bBoreal\s+Forest\b/i, name: "Boreal Forest" },
        { regex: /\bControl\s+Panel\b/i, name: "Control Panel" },
        { regex: /\bemphorosaur[- ]?s\b/i, name: "Emphorosaur-S" },
        { regex: /\bAtomic\s+Alloy\b/i, name: "Atomic Alloy" },
        { regex: /\bBright\s+Water\b/i, name: "Bright Water" },
        { regex: /\bFatal\s+Glitch\b/i, name: "Fatal Glitch" },
        { regex: /\bLeaded\s+Glass\b/i, name: "Leaded Glass" },
        { regex: /\bMaster\s+Piece\b/i, name: "Master Piece" },
        { regex: /\bNight\s+Terror\b/i, name: "Night Terror" },
        { regex: /\bParty\s+Animal\b/i, name: "Party Animal" },
        { regex: /\bBlack\s+Lotus\b/i, name: "Black Lotus" },
        { regex: /\bBlood\s+Tiger\b/i, name: "Blood Tiger" },
        { regex: /\bGolden\s+Coil\b/i, name: "Golden Coil" },
        { regex: /\bHyper\s+Beast\b/i, name: "Hyper Beast" },
        { regex: /\bIcarus\s+Fell\b/i, name: "Icarus Fell" },
        { regex: /\bMoss\s+Quartz\b/i, name: "Moss Quartz" },
        { regex: /\bwash\s+me\s+(?:plz|please)\b/i, name: "Wash me plz" },
        { regex: /\bDark\s+Water\b/i, name: "Dark Water" },
        { regex: /\bPlayer\s+Two\b/i, name: "Player Two" },
        { regex: /\bFizzy\s+POP\b/i, name: "Fizzy POP" },
        { regex: /\bMud[- ]Spec\b/i, name: "Mud-Spec" },
        { regex: /\bRose\s+Hex\b/i, name: "Rose Hex" },
        { regex: /\bHot\s+Rod\b/i, name: "Hot Rod" },
        { regex: /\bStratosphere\b/i, name: "Stratosphere" },
        { regex: /\bLiquidation\b/i, name: "Liquidation" },
        { regex: /\bPrintstream\b/i, name: "Printstream" },
        { regex: /\bDecimator\b/i, name: "Decimator" },
        { regex: /\bFlashback\b/i, name: "Flashback" },
        { regex: /\bNightmare\b/i, name: "Nightmare" },
        { regex: /\bVaporwave\b/i, name: "Vaporwave" },
        { regex: /\bBasilisk\b/i, name: "Basilisk" },
        { regex: /\bBriefing\b/i, name: "Briefing" },
        { regex: /\bElectrum\b/i, name: "Electrum" },
        { regex: /\bGuardian\b/i, name: "Guardian" },
        { regex: /\bSolitude\b/i, name: "Solitude" },
        { regex: /\bVariCamo\b/i, name: "VariCamo" },
        { regex: /\bKnight\b/i, name: "Knight" },
        { regex: /\bCyrex\b/i, name: "Cyrex" },
        { regex: /\bNitro\b/i, name: "Nitro" },
        { regex: /\bFade\b/i, name: "Fade" },
      ],
      "M4A4": [
        { regex: /\bGlobal\s+Offensive\b/i, name: "Global Offensive" },
        { regex: /\bNaval\s+Shred\s+Camo\b/i, name: "Naval Shred Camo" },
        { regex: /\bRadiation\s+Hazard\b/i, name: "Radiation Hazard" },
        { regex: /(?:龍王(?:\s*\(dragon\s+king\))?|\bdragon\s+king\b)/i, name: "龍王 (Dragon King)" },
        { regex: /\bIn\s+Living\s+Color\b/i, name: "In Living Color" },
        { regex: /\bSheet\s+Lightning\b/i, name: "Sheet Lightning" },
        { regex: /\bCyber\s+Security\b/i, name: "Cyber Security" },
        { regex: /\bDark\s+Operative\b/i, name: "Dark Operative" },
        { regex: /\bDesolate\s+Space\b/i, name: "Desolate Space" },
        { regex: /\bThe\s+Battlestar\b/i, name: "The Battlestar" },
        { regex: /\bdesert[- ]strike\b/i, name: "Desert-Strike" },
        { regex: /\bFull\s+Throttle\b/i, name: "Full Throttle" },
        { regex: /\bModern\s+Hunter\b/i, name: "Modern Hunter" },
        { regex: /\bRoyal\s+Paladin\b/i, name: "Royal Paladin" },
        { regex: /\bThe\s+Coalition\b/i, name: "The Coalition" },
        { regex: /\bAeolian\s+Dark\b/i, name: "Aeolian Dark" },
        { regex: /\bDark\s+Blossom\b/i, name: "Dark Blossom" },
        { regex: /\bDesert\s+Storm\b/i, name: "Desert Storm" },
        { regex: /\bEye\s+of\s+Horus\b/i, name: "Eye of Horus" },
        { regex: /\bJungle\s+Tiger\b/i, name: "Jungle Tiger" },
        { regex: /\bBullet\s+Rain\b/i, name: "Bullet Rain" },
        { regex: /\bEvil\s+Daimyo\b/i, name: "Evil Daimyo" },
        { regex: /\bFaded\s+Zebra\b/i, name: "Faded Zebra" },
        { regex: /\bSpider\s+Lily\b/i, name: "Spider Lily" },
        { regex: /\bThe\s+Emperor\b/i, name: "The Emperor" },
        { regex: /\bTooth\s+Fairy\b/i, name: "Tooth Fairy" },
        { regex: /\bUrban\s+DDPAT\b/i, name: "Urban DDPAT" },
        { regex: /\bSteel\s+Work\b/i, name: "Steel Work" },
        { regex: /\bBuzz\s+Kill\b/i, name: "Buzz Kill" },
        { regex: /\bEtch\s+Lord\b/i, name: "Etch Lord" },
        { regex: /\bRed\s+DDPAT\b/i, name: "Red DDPAT" },
        { regex: /\bNeo[- ]Noir\b/i, name: "Neo-Noir" },
        { regex: /\bPoly\s+Mag\b/i, name: "Poly Mag" },
        { regex: /\bX[- ]Ray\b/i, name: "X-Ray" },
        { regex: /\bConverter\b/i, name: "Converter" },
        { regex: /\bMagnesium\b/i, name: "Magnesium" },
        { regex: /\bMainframe\b/i, name: "Mainframe" },
        { regex: /\bZubastick\b/i, name: "Zubastick" },
        { regex: /\bDaybreak\b/i, name: "Daybreak" },
        { regex: /\bHellfire\b/i, name: "Hellfire" },
        { regex: /\bPolysoup\b/i, name: "Polysoup" },
        { regex: /\bPoseidon\b/i, name: "Poseidon" },
        { regex: /\bAsiimov\b/i, name: "Asiimov" },
        { regex: /\bGriffin\b/i, name: "Griffin" },
        { regex: /\bHellish\b/i, name: "Hellish" },
        { regex: /\bTemukau\b/i, name: "Temukau" },
        { regex: /\bTornado\b/i, name: "Tornado" },
        { regex: /\bTurbine\b/i, name: "Turbine" },
        { regex: /\bChoppa\b/i, name: "Choppa" },
        { regex: /\bFalak\b/i, name: "Falak" },
        { regex: /\bZirka\b/i, name: "Zirka" },
        { regex: /\bHowl\b/i, name: "Howl" },
      ],
    },

    buildKnifeMarketHashName: function ({ model, skin, wear, isStatTrak }) {
      if (!model || !skin || !wear) return null;
      const weaponName = CS2_DATA.STEAM_KNIFE_WEAPONS[model] || model;
      const wearObj = CS2_DATA.WEARS.find((w) => w.abbr === wear || w.fullName === wear);
      if (!wearObj) return null;
      const prefix = isStatTrak ? "★ StatTrak™ " : "★ ";
      return `${prefix}${weaponName} | ${skin} (${wearObj.fullName})`;
    },

    buildWeaponMarketHashName: function ({ weapon, skin, wear, isStatTrak, isSouvenir }) {
      if (!weapon || !skin || !wear) return null;
      const wearObj = CS2_DATA.WEARS.find((w) => w.abbr === wear || w.fullName === wear);
      if (!wearObj) return null;
      let prefix = "";
      if (isStatTrak) prefix = "StatTrak™ ";
      else if (isSouvenir) prefix = "Souvenir ";
      return `${prefix}${weapon} | ${skin} (${wearObj.fullName})`;
    },

    buildGloveMarketHashName: function ({ model, skin, wear }) {
      if (!model || !skin || !wear) return null;
      const wearObj = CS2_DATA.WEARS.find((w) => w.abbr === wear || w.fullName === wear);
      if (!wearObj) return null;
      return `★ ${model} | ${skin} (${wearObj.fullName})`;
    },

    fetchCSFloatPrice: async function (marketHashName) {
      if (!marketHashName) return null;

      // When running in content script, delegate to background service worker to bypass page CSP
      if (typeof chrome !== "undefined" && chrome.runtime && chrome.runtime.sendMessage && !chrome.runtime.getBackgroundPage) {
        try {
          const response = await new Promise((resolve) => {
            chrome.runtime.sendMessage(
              { action: "fetchCSFloatPrice", marketHashName },
              (res) => {
                if (chrome.runtime.lastError) {
                  console.warn("[CSFloat Message Warn]:", chrome.runtime.lastError);
                  return resolve(null);
                }
                resolve(res);
              }
            );
          });
          if (response && response.price != null) return response.price;
        } catch (e) {
          console.warn("[CSFloat Background Fetch Warn]:", e);
        }
      }

      // Direct fetch fallback (for background worker, options page, or Node.js)
      try {
        const url = `https://api.openskin.dev/v1/prices/csfloat?item=${encodeURIComponent(marketHashName)}`;
        const response = await fetch(url);
        if (!response.ok) return null;
        const data = await response.json();
        return data.ask != null ? data.ask : null;
      } catch (err) {
        console.error("[CSFloat API Error]:", err);
        return null;
      }
    },
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = CS2_DATA;
  } else {
    root.CS2_DATA = CS2_DATA;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
